#pragma once

#define JS_DEVICE "/dev/input/js0"
#define AXIS_THROTTLE 1
#define AXIS_YAW 0
#define AXIS_ROLL 4
#define AXIS_PITCH 3
#define AXIS_THROTTLE_DIRECTION -1
#define AXIS_YAW_RIGHT_DIRECTION 1
#define AXIS_ROLL_RIGHT_DIRECTION 1
#define AXIS_PITCH_UP_DIRECTION 1

#define CONTROLLER_BUTTON_ARM 9
